# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 步步宝

on:
  workflow_dispatch:
  schedule:
     - cron: '9 * * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BBB_COOKIE: ${{ secrets.BBB_COOKIE }}
         
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/sinagod/CenBoMin.test.git ~/BBB
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.BBB_COOKIE
        run: |
          cd ~/BBB
          npm install
      - name: '运行 【汽车之家极速版】'
        if: env.BBB_COOKIE
        run: |
          cd ~/BBB
          node BBB.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
     
